arch: mobilenet # MobileNet V1
widen_factor: 1.0
checkpoint_fp: /home/ubuntu/murata/Media2Cloud/FastAPIServer/3DFFAFastAPI/Model/weights/mb1_120x120.pth
bfm_fp: /home/ubuntu/murata/Media2Cloud/FastAPIServer/3DFFAFastAPI/Model/configs/bfm_noneck_v3.pkl # or configs/bfm_noneck_v3_slim.pkl
size: 120
num_params: 62
