arch: mobilenet # MobileNet V1
widen_factor: 1.0
checkpoint_fp: /Users/tatsuro/Documents/Media2CloudTutorial/3DFFATorchserve/Model/weights/mb1_120x120.pth
bfm_fp: /Users/tatsuro/Documents/Media2CloudTutorial/3DFFATorchserve/Model/configs/bfm_noneck_v3.pkl # or configs/bfm_noneck_v3_slim.pkl
size: 120
num_params: 62
